# frozen_string_literal: true

source 'https://rubygems.org'

gem 'nokogiri', '~> 1.17', '>= 1.17.2'

gem 'selenium-webdriver', '~> 4.4'

gem 'mime-types', '~> 3.3.1'
gem 'netrc', '~> 0.11.0'
gem 'http-accept', '~> 2.2', '>= 2.2.1'
gem 'http-cookie', '~> 1.0', '>= 1.0.8'
gem 'rest-client', '~> 1.8'
